# Name of this action
name: Automated Testing

# Event triggers on pull request event
on: pull_request

# The jobs this action will run. You can write as many jobs as you want.
jobs:
  # ID of the job
  run-jest-tests:
    # Name of the job as it will be displayed in GitHub
    name: Jest Tests
    # Machine which this action will be run on. For a list of all the machines available/how to run on self hosted machine visit
    runs-on: ubuntu-latest

    # Steps this job must take to complete
    steps:
      # Reference the main branch.
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      # Specify which version of Node this project is using. For more information visit.
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install all dependencies
        run: npm install

      - name: Run Jest Tests
        run: npm run test-unit
        
      - name: Run Cypress Tests
        run: npm run test-e2e-cli
